name    'sohonet-wordpress'
version '1.0.0'
source 'https://github.com/mindriot88/puppet-wordpress'
author 'Jason Pereira'
license 'Apache2'
summary 'Puppet module to set up an instance of wordpress'
description 'Installs wordpress and web server stack.'
project_page 'https://github.com/mindriot88/puppet-wordpress'

## Add dependencies, if any:
dependency 'puppetlabs/concat', '>= 1.2.4'
dependency 'puppetlabs/mysql', '>= 3.6.1'
dependency 'puppetlabs/stdlib', '>= 4.9.0'
dependency 'puppetlabs/apache', '>= 1.6.0'
dependency 'mayflower/php', '>= 3.4.2'
